version: '3.9'

services:
  database_manager:
    build: .
    tty: true
    stdin_open: true
    entrypoint: ./run_tests.sh
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'example'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'aaa123'
      MYSQL_ROOT_PASSWORD: 'aaa123'
    expose:
      - '3306'
    volumes:
      - ./tests/test_db_init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/mysql
      
volumes:
  database: